### PR TITLE
Release build_resolvers with null language version fix

### PR DESCRIPTION
**Pull request by jakemac53**
Also adds a test which validates the behavior

### CODE REVIEW

**Comment by jakemac53** [comment]
Note that it does appear that analyzer gives us the _default_ language version here, and not `null` which would actually likely be what we want for codegen.

It _probably_ doesn't matter because I don't think we allow publishing without an SDK constraint any more, and published codegen files in packages is where this would really cause a problem.

**Comment by jakemac53** [comment]
@scheglov I added a test here that the language version matches the current SDK version if not specified, but it looks like we are getting `2.8` even on a `2.9` sdk?

Is that a bug in analyzer or is there something else I need to do?

**Comment by jakemac53** [comment]
It looks like this is a hardcoded value in the analyzer, https://github.com/dart-lang/sdk/blob/b774160615a741ce40ff6fd8f3bf7bf5f78556c4/pkg/analyzer/lib/src/dart/analysis/experiments.g.dart#L11.

But the SDK constraints in the analyzer here don't align with that version.... :/

**Comment by jakemac53** [comment]
Updating the expect for now to expect `ExperimentStatus.currentVersion` from the analyzer (which is what it will give us internally) - I will file an issue on analyzer about this though.

**Comment by scheglov** [comment]
This works as intended - from the element model we should return the actual language version.
And analyzer returns the the version that it understands as the current version by default.

**Comment by jakemac53** [comment]
Filed https://github.com/dart-lang/sdk/issues/41583

**Pull request merged**
