### PR TITLE
Update dev_compiler_bootstrap to detect baseUrl 

### PR DESCRIPTION
**Pull request by dineshbhosale**
Partial fix for #1087 
Works with service workers, `routerProviders`, `routerProvidersHash`.

### CODE REVIEW

**Comment by jakemac53** [comment]
@chalin would this resolve the issues you were having with deployed ddc apps?

**Comment by natebosch** [comment]
Previous context: https://github.com/dart-lang/build/pull/1330

**Comment by jakemac53** [comment]
Also cc @matanlurey @alorenzen does this seem reasonable to you guys from an angular perspective?

**Comment by matanlurey** [comment]
I don't know enough about how this works, unfortunately.

For AngularDart, there are two ways to set the base URL:
* In the HTML, above
* As a provider

I assume that the former only didn't work, and this makes it work?

**Comment by dineshbhosale** [comment]
Yes,
This will allow to develop using DDC while using different root directories, `http://example.com/abc/` while using `routerProviders` at the same time, not breaking redirect links (for example password reset link) links sent by backend.

**Comment by dineshbhosale** [comment]
Also it is very useful for chrome extensions, because for now there is no other way to set `baseUrl` for chrome extensions.

**Comment by chalin** [comment]
> @chalin would this resolve the issues you were having with deployed ddc apps?

Thanks for the ping @jakemac53. The issue was: _Deployed Angular 5 app results in 404 for require.js_ #896. Looking at this PR now.

**Comment by jakemac53** [comment]
> Thanks for the ping @jakemac53. The issue was: Deployed Angular 5 app results in 404 for require.js #896. Looking at this PR now.

Ok yes - so it looks like you are setting the `<base href="...">` so i think this would resolve the issue potentially?

**Comment by chalin** [comment]
> looks like you are setting the <base href="..."> so i think this would resolve the issue potentially?

Yes, though if we're going to fix the code, I'd clean it up too (e.g., we should be using `===`, etc). I'd also want to ensure that we only accept href's that start with '/'.

I'd suggest something like this:

```js
var baseUrl = (function () {
  var href = '/';
  if (typeof document !== 'undefined') {
    var el = document.getElementsByTagName('base')[0];
    if (el && el.href && el.href.startsWith('/')) href = el.href;
  } else {
    // Attempt to detect --precompiled mode for tests, and set the base url
    // appropriately, otherwise set it to '/'.
    var pathParts = location.pathname.split('/');
    if (pathParts[0] === '') pathParts.shift();
    if (pathParts[1] === 'test') href = '/' + pathParts.slice(0, 2).join('/') + '/';
  }
  return href;
}());
```

Btw, is the "Attempt to detect --precompiled mode" still relevant?

cc @kwalrath

**Comment by dineshbhosale** [comment]
After trying different variations, this one works without any errors

```js
var baseUrl = (function () {
  // Attempt to detect base url using <base href> html tag
  // base href should start with "/"
  if (typeof document !== 'undefined') {
    var el = document.getElementsByTagName('base');
    if (el && el[0] && el[0].href && el[0].href.startsWith('/')){
    	return el[0].href;
    }
  }
  // Attempt to detect --precompiled mode for tests, and set the base url
  // appropriately, otherwise set it to '/'.
  var pathParts = location.pathname.split("/");
  if (pathParts[0] == "") {
    pathParts.shift();
  }
  var baseUrl;
  if (pathParts.length > 1 && pathParts[1] == "test") {
    return "/" + pathParts.slice(0, 2).join("/") + "/";
  }
  return "/";
}());
```

**Comment by jakemac53** [comment]
Ok, I think we are going to go with this change, thanks @dineshbhosale.

Please push a CHANGELOG.md update as well, something along the lines of `dartdevc now respects the <base> tag".

**Comment by jakemac53** [comment]
I went ahead and just pushed the changelog/pubspec updates, will merge on green. Thanks @dineshbhosale!

**Comment by jakemac53** [comment]
Released as 0.3.7+3 of build_web_compilers

**Pull request merged**
