### PR TITLE
Fix typo in exceptions.dart

### PR DESCRIPTION
**Pull request by alikhaleghi76**
Fixed a typo mistake in BuildStepCompletedException class in exceptions.dart

### CODE REVIEW

**Comment by jakemac53** [comment]
Thanks @alikhaleghi76, are you able to sign the CLA?

**Comment by alikhaleghi76** [comment]
> Thanks @alikhaleghi76, are you able to sign the CLA?

You're welcome! 
I signed it after the warning.  There should be no problem now.

**Comment by jakemac53** [comment]
It looks like you have two different emails here - one that made the commit and a different one that you signed with - which is why it is still failing the CLA check. Can you sign again with the email that you used to create the commit?

**Comment by alikhaleghi76** [comment]
> It looks like you have two different emails here - one that made the commit and a different one that you signed with - which is why it is still failing the CLA check. Can you sign again with the email that you used to create the commit?

Sorry, you are right. 
It's ok now.

**Pull request merged**
