### PR TITLE
build_runner: fix version and SDK version constraint

### PR DESCRIPTION
**Pull request by kevmoo**
Update mono_repo config to test supported SDKs

### CODE REVIEW

**Review by jakemac53 — COMMENTED** [review]
changelog?

**Comment by kevmoo** [comment]
> changelog?

already happened. This just updated the pubspec to match!

**Review by natebosch — APPROVED** [review]

**Review by jakemac53 — APPROVED** [review]

**Comment by kevmoo** [comment]
Looks like the build_runner e2e test is now failing on 2.10 – this is due to me adding back testing on 2.10

**Comment by kevmoo** [comment]
Thoughts on what we should do there?

**Comment by jakemac53** [comment]
It looks like a test that can never run on 2.10 because it sets 2.12 as the language version, but I don't see any reason it needs to do that. We can just remove the language marker probably.

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/pull/2941

**Pull request merged**
