### PR TITLE
Fix analysis warnings for non-null error result

### PR DESCRIPTION
**Pull request by natebosch**

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]

**Review by jakemac53 — APPROVED** [review]

**Review by kevmoo — APPROVED** [review]

**Comment by kevmoo** [comment]
This due to a change in pkg:analyzer, right?

Do we need to bump the min version of analyzer supported? Something is non-nullable now that was nullable...

**Comment by jakemac53** [comment]
Oh geeze ya you are right @kevmoo.

**Review by jakemac53 — DISMISSED** [review]
see kevins comment :)

**Comment by natebosch** [comment]
> Do we need to bump the min version of analyzer supported?

Yes we do. I guess it's more helpful if I push my commits rather than just site with them locally...

**Pull request merged**
