### PR TITLE
Remove support for module reloads

### PR DESCRIPTION
**Pull request by simolus3**
Following the suggestion from @jakemac53:

>  Honestly we could just finally remove entirely the ability to hot reload from this package, we really expect people to go through webdev for that now and the implementation in this package is likely to bitrot.

This avoids some uncertainty related to a `pkg:graphs` change.

### CODE REVIEW

**Comment by simolus3** [comment]
How should we fix the markdown link failure? Remove the reference from older changelog entries?

**Comment by jakemac53** [comment]
> How should we fix the markdown link failure? Remove the reference from older changelog entries?

That seems reasonable ya

**Comment by jakemac53** [comment]
@grouma just to confirm - webdev isn't relying on this flag right?

**Comment by grouma** [comment]
> @grouma just to confirm - webdev isn't relying on this flag right?

Shouldn't be. The hot restart logic is now located in `package:dwds` and used by webdev / Flutter Tools.

**Review by jakemac53 — APPROVED** [review]

**Pull request merged**
