### PR TITLE
Allow latest analyzer (0.41.0)

### PR DESCRIPTION
**Pull request by jakemac53**
Closes https://github.com/dart-lang/build/issues/2906

### CODE REVIEW

**Comment by jakemac53** [comment]
Getting all of these tests passing/resolving seems like a lost cause right now, but its down to just a few integration tests that I can't get to run, and everything looks good as far as the analyzer goes.

**Comment by jcollins-g** [comment]
pinging with hope for this landing and publishing soon :-)

**Comment by jakemac53** [comment]
> pinging with hope for this landing and publishing soon :-)

Ya I will pick it back up today, I think we might be in a better state now with respect to our deps allowing analyzer.

**Comment by jakemac53** [comment]
Pub solves are looking good, I confirmed locally everything can get the latest, and also _required_ the latest in a few of our e2e tests.

**Review by natebosch — APPROVED** [review]
Why do we need the dependency overrides? Was that just to be able to `pub upgrade` and get the latest? Should we remove before submitting?

**Comment by jakemac53** [comment]
@natebosch I want the tests to run with the latest yes. Removing them before submitting sgtm.

**Pull request merged**
