### PR TITLE
Add colors based on severity

### PR DESCRIPTION
**Pull request by jakemac53**
This only colors the `[${record.level}]` portion, so its not overly obnoxious, lmk what you think.

### CODE REVIEW

**Comment by kegluneq** [comment]
Seems fine to me - what does this do on Windows?

**Comment by jakemac53** [comment]
Heh, good question. I will try to figure that out.

**Comment by jakemac53** [comment]
OK, I just put in a thing to disable colors on windows for now, as windows support as a whole needs to be evaluated.

**Comment by kegluneq** [comment]
I'd vote for a helper function to avoid the logic duplication, but it doesn't seem terribly urgent. Up to you.

LGTM.

**Pull request merged**
