### PR TITLE
WIP: validate SDK versions

### PR DESCRIPTION
**Pull request by kevmoo**
Let's be explicit about the real required SDK

### CODE REVIEW

**Comment by natebosch** [comment]
That's a lot of versions to test. What value are we getting out of all that work?

**Comment by kevmoo** [comment]
Figuring where and why we have the 2.0 sdk constraint

**Comment by natebosch** [comment]
Bumped that in anticipation of using the latest code_builder

**Comment by kevmoo** [comment]
Let's hold back bumps as.long as possible. 1.24 folks want json serial

**Comment by natebosch** [comment]
@matanlurey - any thoughts on this?

**Comment by matanlurey** [comment]
This is just not realistic. We need to focus on our MVP vision, not hypothetical customers.

My vote is latest dev release only until we are stable and shipping 2.0.

**Pull request closed without merging**
