### PR TITLE
add a warning if a build.yml file is found in the doctor command

### PR DESCRIPTION
**Pull request by jakemac53**
Fixes https://github.com/dart-lang/build/issues/3615

Note that this would only give the warning if running the `doctor` command, which people may not be in the habit of running, but is typically where we put these kinds of diagnostics.

@schaipipat out of curiosity were you aware of the doctor command? Would this have helped you or not?

### CODE REVIEW

**Review by natebosch — APPROVED** [review]
This LGTM. We could also consider a verbose log like "No build.yaml configuration file, using defaults." and a different verbose log for when the file is read. Anyone running with  `-v` could see this without having to run a separate `doctor` command.

**Comment by jakemac53** [comment]
I tried originally putting this into the code that actually looks for these files, but it ended up getting complicated because those APIs are actually called for all transitive packages deps, and don't have access to a logging API. So this was the simplest approach.

**Comment by schaipipat** [comment]
@jakemac53 Not really. All the tools that using `build_runner` never mention about `doctor` command so I haven't run it when I start facing the issue.

**Comment by jakemac53** [comment]
I am going to go ahead and land this because it is better than not having anything - longer term I think we need to figure out how to promote the `doctor` command more I think.

**Pull request merged**
