### PR TITLE
anaysis_options: Quote the excludes – causing YAML parsing issues

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
TBR

**Comment by natebosch** [comment]
Lgtm

Where does this cause issues?

**Comment by kevmoo** [comment]
> Where does this cause issues?

Repo manager was blowing up when doing a yaml decode

```
Error on line 11, column 7: Undefined alias.
    - **/goldens/**
      ^^^^^^^^^^^^^
package:yaml/src/loader.dart 108:5               Loader._loadAlias
package:yaml/src/loader.dart 80:16               Loader._loadNode
package:yaml/src/loader.dart 141:20              Loader._loadSequence
package:yaml/src/loader.dart 84:16               Loader._loadNode
package:yaml/src/loader.dart 165:19              Loader._loadMapping
package:yaml/src/loader.dart 86:16               Loader._loadNode
package:yaml/src/loader.dart 165:19              Loader._loadMapping
package:yaml/src/loader.dart 86:16               Loader._loadNode
package:yaml/src/loader.dart 62:20               Loader._loadDocument
package:yaml/src/loader.dart 54:20               Loader.load
package:yaml/yaml.dart 51:25                     loadYamlDocument
package:yaml/yaml.dart 42:5                      loadYamlNode
package:yaml/yaml.dart 34:5                      loadYaml
```

**Comment by kevmoo** [comment]
Zero clue how analysis code is parsing this without an issue...

**Comment by natebosch** [comment]
Or analysis may have been silently failing to do any work...

**Comment by jakemac53** [comment]
Hah, for the longest time we were trying to exclude the "e2e_example" dir but I kept getting analysis errors for it. I bet this is why....

**Comment by kevmoo** [comment]
🤷‍♂️

**Comment by natebosch** [comment]
Filed https://github.com/dart-lang/sdk/issues/31355

**Comment by kevmoo** [comment]
Awesome.

**Pull request merged**
