### PR TITLE
fix(runner_core): don't double-initialize builders

### PR DESCRIPTION
**Pull request by kevmoo**
expandedPhases is an Iterable that is accessed twice with a call to
.where causing double iteartion – and double initialization of each
builder

This code goes through the same items, but only once.

### CODE REVIEW

**Comment by kevmoo** [comment]
Oops! Not sure how to test this...

**Comment by jakemac53** [comment]
You should be able to make a builder factory that increments a global counter and expect it to have a certain value afterwords?

**Comment by kevmoo** [comment]
Can I land this and leave the test for a TODO for one of you guys w/ more context?

**Comment by jakemac53** [comment]
How about I just push a test to this branch, it shouldn't take to long

**Comment by jakemac53** [comment]
test added

**Comment by natebosch** [comment]
tweaked it some to keep it closer to the old pattern and add a `toList()` to avoid the double instantiate.  In the longer term once we can use `whereType` we'll want it to look like this rather than a for loop.

**Comment by jakemac53** [comment]
3 people on one PR! its a new record! :medal_sports:

**Comment by kevmoo** [comment]
So I will land once travis is green? Thanks for your help here!

**Pull request merged**
