### PR TITLE
add option to skip the prompt to delete existing outputs

### PR DESCRIPTION
**Pull request by jakemac53**

### CODE REVIEW

**Comment by kevmoo** [comment]
LGTM - merged

**Comment by zoechi** [comment]
How does build know whether the files were generated by it or not after build was restarted and previously generated files still exist?

**Comment by kevmoo** [comment]
It sees if the output is referenced in `.dart_tools/build/[sha]/asset_graph.json`

**Comment by zoechi** [comment]
I see, thanks!

**Pull request merged**
