### PR TITLE
Use new frontend with Dart2Js

### PR DESCRIPTION
**Pull request by natebosch**
- Allow creating files at the root of the scratchspace.
- Construct a .packages file for the entrypoint before invoking Dart2Js

### CODE REVIEW

**Comment by Cretezy** [comment]
We're waiting for the `scratch-pad-0.2.0` release to move this PR into https://github.com/pulyaevskiy/node-interop (https://github.com/pulyaevskiy/node-interop/issues/8).

**Comment by kevmoo** [comment]
I'm sure @natebosch will be on it first thing tomorrow 😄

**Comment by Cretezy** [comment]
Sounds good! Thanks everyone for this PR!

**Comment by natebosch** [comment]
@Cretezy - `scratch_space` is published.

**Pull request merged**
