### PR TITLE
s/hide Logger/show AnalysisOptions

### PR DESCRIPTION
**Pull request by MichaelRFairhurst**
This will unblock us from removing Logger as a part of the analysis engine namespace. (hiding a non-exist term is a build breaking error in g3)

### CODE REVIEW

**Comment by jakemac53** [comment]
Do we need to publish this soon or will this be in the next analyzer release and we can wait until then?

**Comment by MichaelRFairhurst** [comment]
Technically this is not a breaking change. It breaks google3 just like unused imports do. But it won't need to be published. Obviously better/safer to though!

**Comment by jakemac53** [comment]
Ok - can you update the pubspec/changelog to `1.2.3-dev` (changelog can just have a very brief entry but something should exist for each pending or released version)

**Comment by MichaelRFairhurst** [comment]
OK, done!

**Comment by MichaelRFairhurst** [comment]
@jakemac do you prefer merge, squash, or rebase?

**Comment by jakemac53** [comment]
We generally prefer squash & merge

**Comment by jakemac53** [comment]
The presubmit error does seem related to this - https://travis-ci.org/dart-lang/build/jobs/605197109#L661

**Comment by jakemac53** [comment]
(or possibly its a bug in the lint?)

**Comment by MichaelRFairhurst** [comment]
I changed `[AnalysisContext]` to `\`AnalysisContext\``, but if you prefer, can `show AnalysisContext`.

**Comment by jakemac53** [comment]
What you did is fine - its weird to add something to the scope just for a doc comment imo :D

**Pull request merged**
