### PR TITLE
update to stable 3.5 release

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Review by jakemac53 — COMMENTED** [review]
We will need to bump the versions to `-wip` ones and update changelogs as well for many of these.

**Review by jakemac53 — APPROVED** [review]

**Comment by kevmoo** [comment]
The one markdown link check issue is just a silly pub.dev thingy. landing.

**Comment by jakemac53** [comment]
@kevmoo do you know if there is an issue filed or should I file one? Pana seems to not work with workspaces

**Comment by kevmoo** [comment]
https://github.com/dart-lang/pana/issues/1369 ?

**Pull request merged**
