### PR TITLE
Add OSX support to travis.

### PR DESCRIPTION
**Pull request by matanlurey**
(Not ready to merge yet)

Fixes https://github.com/dart-lang/build/issues/653.

### CODE REVIEW

**Comment by jakemac53** [comment]
Looks like the only issue is the new chrome addon change isn't working on the linux boxes... any ideas?

**Comment by jakemac53** [comment]
Ah, looks like the chrome addon doesn't automatically start xvfb - added that part back to the before_install section per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI and it looks like it is going to be green now.

**Comment by matanlurey** [comment]
Woohoo!

**Comment by jakemac53** [comment]
Looks like there is a bit of a backlog for travis mac builds due to https://www.traviscistatus.com/incidents/1vd05j8y0yfq but that should be a short term thing

**Comment by jakemac53** [comment]
hmm actually this looks like a common issue https://www.traviscistatus.com/#month. They don't appear to ever run more than 180 mac jobs and the queue often gets pretty long... not sure if that will be a blocker for us or not. We can try it out for a while and see how annoying it gets in any case.

**Comment by natebosch** [comment]
Should we limit it to the e2e tests on mac?

**Comment by jakemac53** [comment]
See https://blog.travis-ci.com/2017-09-22-macos-update as well talking about this issue

**Comment by jakemac53** [comment]
Limiting to e2e tests won't help us much (they will still be queued on the main queue). However we could do it just as good travis citizens since the macos builders are limited.

**Comment by matanlurey** [comment]
There sounds fine to limit to e2e!

**Comment by jakemac53** [comment]
Oh and of course the xfvb commands fail on osx lol.

Also, given the time it takes to queue these jobs it seems prudent try and see if we can run them only on commits to master, and not for pull requests.

**Comment by matanlurey** [comment]
@jakemac53 Want to just add the `branches: [master]` and call it done?

**Comment by matanlurey** [comment]
After the xfvb fix, of course. We can conditionally run that on != OSX.

**Comment by natebosch** [comment]
> Want to just add the `branches: [master]` and call it done?

We have the config to only run on master, the problem is that it's still too slow for pull requests.
Ideally I think what we'd want is to run on linux for pull requests, and on mac with a cron or something. That way we aren't slowed down getting stuff merged, but we notice within a day if we do break mac.

**Comment by matanlurey** [comment]
It looks like it took at most 4 minutes per task with e2e_example taking ~1.5 minutes:
https://travis-ci.org/dart-lang/build/jobs/313169150

Why don't we start with just e2e_example for OSX like Windows?

**Comment by natebosch** [comment]
The problem is that the osx tasks take a long time to get started. Once they start they run quick enough

**Comment by natebosch** [comment]
There is too much delay before the builds even get started. I don't think we want to enable this until Travis has lower queue times for OSX

**Pull request closed without merging**
