### PR TITLE
Extend analyzer range to 0.34

### PR DESCRIPTION
**Pull request by jcollins-g**
We can't really wait on extending the range anymore to allow for a new analyzer publish to be used with dartdoc.  Since we're only publishing alphas at this time this PR shouldn't accidentally add new versions to other users of build unless they specifically request them.

@bwilkerson

### CODE REVIEW

**Comment by jcollins-g** [comment]
I'm happy to update pubspecs/CHANGELOG/etc or other housekeeping tasks you'd need done to publish these packages as well.  Please let me know if you'd like to do that and if +1 versions are OK for this sort of change for you.

**Comment by jakemac53** [comment]
The primary issue with doing a constraint like this is we can't shield ourselves against any breakages that come up with the actual 0.33 release (and in fact I think our tests would still just run against the stable 0.32.x versions).

If we need to publish with a version that supports 0.33.0-alpha.0 then I think setting the upper bound to exactly that (`<=0.33.0-alpha.0`) is preferable. cc @natebosch thoughts?

**Comment by natebosch** [comment]
yeah I don't think pub wants to resolve to `0.33.0-alpha.0` if the upper end of the constraint is `<0.34.0`. I think you want `<=0.33.0-alpha.0` on the upper end - but we'll have to bump for every alpha that you need.

A bug fix version bump is fine. That `+1` for packages with a leading `0` in the major version, or the last dot for packages with a major version other than `0`.

**Comment by jcollins-g** [comment]
@jakemac53 Yes, you're right.  If we publish a broken stable package, we'd have to publish a fixed stable package in the same range to correct the issue.

@natebosch That was actually the intent -- to not automatically resolve an alpha version with pub _unless_ a package that depends on build specifies that alpha version intentionally (which would be the case for dartdoc, which is why I am advocating for the change).  Right now you can't do that without dependency overrides because of the limited ranges.

**Comment by jcollins-g** [comment]
@natebosch pointed out offline, there is a workaround (removing dev dependencies from dartdoc pre-publish) that would allow a version of dartdoc to be published without this, so this is not technically blocking us.

**Comment by natebosch** [comment]
Synced with Jake. We're fine publishing with `<0.34.0` if you think there aren't going to be any further breaking changes that will impact us. Though, if that's the case it's not clear why we aren't publishing non-alpha analyzer today - maybe you expect breaking changes that would impact users _other_ than build?

In any case we can merge this once pubspecs and changelogs are updated and I can start publishing.

**Comment by natebosch** [comment]
> the impact of non-alpha versions on the ecosystem has historically been very large

Once we publish any package with a constraint of `<=0.34.0` I think that impact has been felt. You won't be able to publish `0.33.0-alpha.1` with breaking changes, so you may as well publish `0.33.0` then `0.33.1` etc. I think the new pub solver doesn't care as much if there are a lot of `0.33.x` non-alpha versions.

**Comment by natebosch** [comment]
Sounds good. will put it on hold for now.

**Comment by jcollins-g** [comment]
@natebosch  Can we take another look now that 0.33.0 is [published](https://pub.dartlang.org/packages/analyzer/versions/0.33.0) for analyzer?  I have restarted the Travis tests  but I don't have access to rekick AppVeyor.

**Comment by jakemac53** [comment]
Kicked off a new build @jcollins-g, with the new version of analyzer we should be good to go.

**Pull request merged**
