### PR TITLE
build_test: Remove unused imports of dart:async

### PR DESCRIPTION
**Pull request by srawlins**
As of Dart 2.1, Future/Stream have been exported from dart:core.

### CODE REVIEW

**Comment by jakemac53** [comment]
Please update the pubspec/changelog (just a patch release, 1.3.1-dev). Please add an entry for the version in the changelog but you do not need to leave any notes.

Note that when you create prs you can select an option so that maintainers can push to the branch which helps with some of this stuff, no reason not to check that box in the future :).

**Comment by srawlins** [comment]
> Note that when you create prs you can select an option so that maintainers can push to the branch which helps with some of this stuff, no reason not to check that box in the future :).

Hmm it looks checked to me...

**Comment by jakemac53** [comment]
> Hmm it looks checked to me...

huh, weird I couldn't push to it :(

**Comment by natebosch** [comment]
> huh, weird I couldn't push to it :(

You need to manually add a git remote for the other fork.

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
> You need to manually add a git remote for the other fork.

Ya I did that 🤷‍♂️

**Pull request merged**
