### PR TITLE
Configure analysis options.

### PR DESCRIPTION
**Pull request by matanlurey**
Closes https://github.com/dart-lang/build/issues/642.

This ... might be tough, if we have folks relying on the current behavior. I'm assuming this should probably be `0.5.0`, but I'm also open for considering the current behavior as a bug since it (a) wasn't using strong mode and (b) was unintentionally different than `bazel_codegen`.

Added two tests as well.

/cc @kevmoo

### CODE REVIEW

**Comment by natebosch** [comment]
I think we do want to release this as a breaking change, and we'll want to wait for build_runner 0.7.0 to pull it to that package since most users only see it through that dependency.

We'll also want to check the impact on performance. We're probably buying back more performance by not analyzing method bodies than we're losing preserving comments so I bet we'll come out ahead on this change overall.

**Comment by matanlurey** [comment]
@natebosch Do you want me to still land this PR to MASTER?

I'll update the CHANGELOG and pubspec accordingly.

**Comment by natebosch** [comment]
Let's hold off on landing until next week, I'll try to get a rough idea of the performance early next week and then we can merge.

We're blocked on publishing the breaking change version of build_runner for a little while so we can't take advantage of this until then.

**Comment by matanlurey** [comment]
Sg. Do we have any performance benchmarks as part of this repo?

**Comment by natebosch** [comment]
No formal benchmarks. My plan was to pick a medium size build and do a few runs with `time` just to get a rough idea.

**Comment by matanlurey** [comment]
Sg. `gwt_mail_sample` might be a good target to convert and benchmark.

**Comment by jakemac53** [comment]
LGTM assuming no significant perf issues

**Comment by natebosch** [comment]
I ran a few builds on angular_components_example before and after this change. I didn't see any change in the overall build time.
If there is any difference here it's likely dominated by other factors. I think we can land this as a breaking change.

**Comment by matanlurey** [comment]
@natebosch Do you want me to land it today?

**Comment by natebosch** [comment]
Anytime is fine once the pubspec is updated. We won't be able to take advantage in build_runner until the next breaking release. I added a note to #628 to keep track

**Comment by matanlurey** [comment]
Great. I'll land it sometime this afternoon.

**Comment by matanlurey** [comment]
@natebosch How should I land this?

I need to add the following to be able to run `pub get`:

```yaml
dependency_overrides:
  # TODO: Remove after a version is published that supports 0.5.0.
  build_test:
    path: ../build_test
```

We might want to add a RELEASE.md or something for the dirty details of updating these.

**Comment by matanlurey** [comment]
Also, https://github.com/dart-lang/pub/issues/1745.

**Comment by natebosch** [comment]
Yeah we typically add the `dependency_override` sections as necessary to get Travis to pass, then right before publishing we remove them and expect Travis to fail until everything is published.

It's not a fun process but without an atomic submit we don't have much better.

I think in this case it would also be fine to preemptively publish `build_test` with a constraint of <0.6.0

**Comment by matanlurey** [comment]
That might be cleanest. I'll send you a PR for that first.

**Comment by natebosch** [comment]
build_test is published allowing 0.5.0

The pub get should work now with a version bump on build_barback.

**Comment by matanlurey** [comment]
@natebosch PTAL again before I merge.

**Pull request merged**
