### PR TITLE
Use JsonSerializable for build_config parsing

### PR DESCRIPTION
**Pull request by jakemac53**
There is a little bit of weirdness here which we can hopefully resolve eventually with fixes from JsonSerializable, but this gets the vm tests passing with --preview-dart-2, and gives us pretty nice mostly-automatic error checking and reporting.

As an example, this build.yaml:

```yaml
targets:
  $default:
    sources:
      include: foo
```

Gives this error:

```
[SEVERE] Failed to parse `build.yaml` for provides_builder.
Invalid argument(s): line 4, column 7: Could not create `InputSet`.
Unsupported value for `include`: type 'String' is not a subtype of type 'List' in type cast

      include: foo
      ^^^^^^^
```

And we have custom errors that look nice as well, for a missing `$default` target for instance:

```yaml
targets:
  floop:
    sources:
      - lib/foo.dart
```

Gives this custom error:

```
[SEVERE] Failed to parse `build.yaml` for <package-here>.
Invalid argument(s): line 1, column 1: Could not create `BuildConfig`.
Unsupported value for `targets`: Must specify a target with the name `provides_builder` or `$default`.

targets:
^^^^^^^
```

The primary thing this doesn't support right now is error reporting for unrecognized keys. I was thinking I would try and add that as a followup, but JsonSerializable should be able to add it by default as well so that might be wasted effort, cc @kevmoo.

Also note that I ended up using a combination of both zones and expandos to get around the issues with the `package` and `key` fields which don't exist in the actual yaml values.

### CODE REVIEW

**Comment by natebosch** [comment]
> ```
> Unsupported value for `include`: type 'String' is not a subtype of type 'List' in type cast
> ```

I thought we supported automatically turning this into a `List<String>` for `include`?

**Comment by jakemac53** [comment]
> I thought we supported automatically turning this into a List<String> for include?

Oh, I didn't think so but I could support that in this system still.

**Comment by natebosch** [comment]
Hmm, double the checking the code I don't see that handling... perhaps I'm misremembered.

**Comment by jakemac53** [comment]
> Hmm, double the checking the code I don't see that handling... perhaps I'm misremembered.

I tried to retain all the custom logic we originally had in parse.dart, I think I got it all.

**Comment by jakemac53** [comment]
Fixes https://github.com/dart-lang/build/issues/1293

**Pull request merged**
