### PR TITLE
scratch_space: remove dev dep on build_vm_compilers

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
Should we also remove build_runner/build_test?

**Comment by kevmoo** [comment]
> Should we also remove build_runner/build_test? Also might want to update the mono repo config to run tests normally if it doesn't already?

Uh...not sure.

This repo *does* use `pub run build_runner test` – should it not?

**Comment by jakemac53** [comment]
> This repo _does_ use `pub run build_runner test` – should it not?

Not once we remove build_vm_compilers (there isn't any value its providing after that)

**Comment by kevmoo** [comment]
> > This repo _does_ use `pub run build_runner test` – should it not?
> 
> Not once we remove build_vm_compilers (there isn't any value its providing after that)

ack – PTAL

**Review by jakemac53 — APPROVED** [review]

**Pull request merged**
