### PR TITLE
check for placeholders when building a target graph from a package graph

### PR DESCRIPTION
**Pull request by jakemac53**
Fixes https://github.com/dart-lang/build/issues/2531

Logs a warning if any required placeholders are not included in any target for a package.

### CODE REVIEW

**Comment by jakemac53** [comment]
I don't really like the idea of adding any magic here personally, I would prefer to just log the warning and let people fix it on their own. Otherwise they won't fix it, and then later on when they introduce some ambiguity (with another target for instance) they will run into problems.

**Comment by natebosch** [comment]
Can this surface in a dependency that has an incorrect `build.yaml`? Maybe they defined a target in order to get some codegen and never tried with `build_web_compilers` or `build_vm_compilers`. If a user sees this warning in a dependency, would they need to add a `<package>.build.yaml` to get around it?

**Comment by jakemac53** [comment]
It does warn about any build.yaml it finds, yes. 

That is why I only made this a warning - any build which previously worked will still work, but you may get a warning if some dependency is not set up properly.

They could also add a `<package>.build.yaml` to hide the warning.

**Comment by jakemac53** [comment]
Note also that this isn't specific at all to build_vm_compilers or build_web_compilers - its a general requirement now.

**Pull request merged**
