### PR TITLE
Put a tight upper bound on SDK

### PR DESCRIPTION
**Pull request by natebosch**
Since there are open questions around enabling const inlining in CFE
we're not confident we won't need a new flag or something used for the
kernel worker. Add a tight upper bound constraint so that we can adjust
if necessary.

### CODE REVIEW

**Comment by kevmoo** [comment]
Do we want this, or just to publish a new release when the SDK updates?

The problem w/ this? When someone updates to Dart 2.4.0 or similar, they will roll BACK to an older version, which is really weird...right?

**Comment by natebosch** [comment]
> Do we want this, or just to publish a new release when the SDK updates?

Depends on how quickly we can react to it I guess?

> When someone updates to Dart 2.4.0 or similar, they will roll BACK to an older version, which is really weird...right?

Not if they have `build_web_compilers: ^2.0.0` which we would hope for. They'd instead get an eager failure.

**Comment by kevmoo** [comment]
We'll have to scramble the second a dev SDK comes out or our bots will all
start failing.

I guess it depends on how paranoid we are...

**Comment by jakemac53** [comment]
We should do this for build_modules too? Although I guess it is to late for that and this can sort of handle it.

**Comment by natebosch** [comment]
> We should do this for build_modules too? Although I guess it is to late for that and this can sort of handle it.

Yeah my thinking was that it would get handled by this package since that's where the usage matters.

> what will this do to our cron job runs?

It would make them fail once a new SDK is released.

**Comment by jakemac53** [comment]
> It would make them fail once a new SDK is released.

I think it will make them fail as soon as any build on the bots happens with the next sdk version? (basically immediately)

**Comment by kevmoo** [comment]
> > It would make them fail once a new SDK is released.
> 
> I think it will make them fail as soon as any build on the bots happens with the next sdk version? (basically immediately)

Then we bump it and see if it's not broken, etc...

I think this gives us way more hassle than it's worth...

**Comment by jakemac53** [comment]
I wonder if we shouldn't leave the upper constraint higher in the repo but reduce it when we actually publish? It would be a bit interesting to try and enforce that though (and a single mistake ruins it forever).

**Comment by jakemac53** [comment]
aaand I released 2.0 already but we never got this in so I guess we should just close it :grimacing:

**Pull request closed without merging**
