### PR TITLE
Fix daemon_test.dart

### PR DESCRIPTION
**Pull request by a-siva**
Remove @dart specification from daemon_test.dart in preparation for https://dart-review.googlesource.com/c/sdk/+/261140.
This is based on the observation from @emmanuel-p

### CODE REVIEW

**Comment by jakemac53** [comment]
That change is likely to break a whole lot more than this test.....

**Comment by jakemac53** [comment]
I think that change likely requires some additional work in any package that spawns a dart isolate or program - at least if they do it from source?

Do the compile commands still do the auto-detection? We rely on this auto detection all over the place.

**Review by jakemac53 — APPROVED** [review]
I will go ahead and approve/merge this anyways as we should be able to run with sound null safety now

**Comment by a-siva** [comment]
> 
> Do the compile commands still do the auto-detection? We rely on this auto detection all over the place.

They will continue to do auto detection in Dart 2.19 and the CL that disables auto detection will land after the branch cut for the final beta of Dart 2.19.

**Pull request merged**
