### PR TITLE
Backport: Don't rethrow file watcher errors, just log them at severe level (#3165)

### PR DESCRIPTION
**Pull request by jakemac53**
Backports #3165 to the last angular compatible version of build_runner.

cc @insinfo can you try this one and confirm if it works?

```yaml
dependency_overrides:
  build_runner:
    git:
      url: https://github.com/dart-lang/build.git
      ref: backport-watcher-fix
      path: build_runner
```

### CODE REVIEW

**Review by natebosch — APPROVED** [review]

**Comment by insinfo** [comment]
the dependencies were resolved with this version, one more thing that I found strange with this version is that now it heals this severe LOG message all the time, before it it only happened the second time


```
PS D:\MyDartProjects\portal_turismo\turismo_browser> webdev build
[INFO] Reading cached asset graph completed, took 918ms
[INFO] Checking for updates since last build completed, took 10.0s
[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds. completed, took 4.8s
[INFO] Building new asset graph completed, took 3.3s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[WARNING] No actions completed for 15.0s, waiting on:
  - build_web_compilers:entrypoint on web/main.dart

[INFO] build_web_compilers:entrypoint on web/main.dart: Compiled 19,459,065 characters Dart to 2,354,547 characters JavaScript in 24.7 seconds
Dart file org-dartlang-app:\\\web\main.dart compiled to JavaScript: web/main.dart.js

[WARNING] No actions completed for 15.1s, waiting on:
  - build_web_compilers:entrypoint on web/main.dart

[INFO] Running build completed, took 1m 36s
[INFO] Caching finalized dependency graph completed, took 519ms
[INFO] Reading manifest at build\.build.manifest completed, took 19ms
[INFO] Deleting previous outputs in `build` completed, took 385ms

If you see this consistently then it is recommended that you enable the polling file watcher with --use-polling-watcher.FileSystemException: Directory watcher closed unexpectedly, path = 'd:\mydartprojects\portal_turismo\turismo_browser'

[INFO] Creating merged output dir `build` completed, took 10.8s
[INFO] Writing asset manifest completed, took 3ms
[INFO] Succeeded after 1m 47s with 5377 outputs (14123 actions)
PS D:\MyDartProjects\portal_turismo\turismo_browser> webdev build
[INFO] Reading cached asset graph completed, took 558ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 406ms
[INFO] Caching finalized dependency graph completed, took 476ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 245ms

If you see this consistently then it is recommended that you enable the polling file watcher with --use-polling-watcher.FileSystemException: Directory watcher closed unexpectedly, path = 'd:\mydartprojects\portal_turismo\turismo_browser'

[INFO] Creating merged output dir `build` completed, took 2.9s
[INFO] Writing asset manifest completed, took 5ms
[INFO] Succeeded after 4.1s with 0 outputs (0 actions)
PS D:\MyDartProjects\portal_turismo\turismo_browser> webdev build
[INFO] Reading cached asset graph completed, took 567ms
[INFO] Checking for updates since last build completed, took 1.3s
[INFO] Running build completed, took 432ms
[INFO] Caching finalized dependency graph completed, took 528ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 540ms
[SEVERE] Error from directory watcher for package:turismo_browser

If you see this consistently then it is recommended that you enable the polling file watcher with --use-polling-watcher.FileSystemException: Directory watcher closed unexpectedly, path = 'd:\mydartprojects\portal_turismo\turismo_browser'

[INFO] Creating merged output dir `build` completed, took 2.3s
[INFO] Writing asset manifest completed, took 80ms
[INFO] Succeeded after 3.9s with 0 outputs (0 actions)
PS D:\MyDartProjects\portal_turismo\turismo_browser> webdev build
[INFO] Reading cached asset graph completed, took 558ms
[INFO] Checking for updates since last build completed, took 1.2s
[INFO] Running build completed, took 427ms
[INFO] Caching finalized dependency graph completed, took 599ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 463ms
[SEVERE] Error from directory watcher for package:turismo_browser

If you see this consistently then it is recommended that you enable the polling file watcher with --use-polling-watcher.FileSystemException: Directory watcher closed unexpectedly, path = 'd:\mydartprojects\portal_turismo\turismo_browser'

[INFO] Creating merged output dir `build` completed, took 2.0s
[INFO] Writing asset manifest completed, took 2ms
[INFO] Succeeded after 3.6s with 0 outputs (0 actions)
PS D:\MyDartProjects\portal_turismo\turismo_browser> webdev build
[INFO] Reading cached asset graph completed, took 558ms
[INFO] Checking for updates since last build completed, took 1.1s
[INFO] Running build completed, took 412ms
[INFO] Caching finalized dependency graph completed, took 577ms
[INFO] Reading manifest at build\.build.manifest completed, took 0ms
[INFO] Deleting previous outputs in `build` completed, took 260ms
[SEVERE] Error from directory watcher for package:turismo_browser

If you see this consistently then it is recommended that you enable the polling file watcher with --use-polling-watcher.FileSystemException: Directory watcher closed unexpectedly, path = 'd:\mydartprojects\portal_turismo\turismo_browser'

[INFO] Creating merged output dir `build` completed, took 2.4s
[INFO] Writing asset manifest completed, took 2ms
[INFO] Succeeded after 3.7s with 0 outputs (0 actions)
PS D:\MyDartProjects\portal_turismo\turismo_browser> 
```
```
pub get
Resolving dependencies...
  _fe_analyzer_shared 12.0.0 (23.0.0 available)
  analyzer 0.40.6 (2.0.0 available)
  archive 2.0.13 (3.1.2 available)
  args 1.6.0 (2.2.0 available)
  async 2.4.2 (2.8.1 available)
  bazel_worker 0.1.25 (1.0.0 available)       
  boolean_selector 2.0.0 (2.1.0 available)    
  build 1.6.0 (2.1.0 available)
  build_config 0.4.5 (1.0.0 available)        
  build_daemon 2.1.4 (3.0.0 available)        
  build_modules 3.0.2 (4.0.1 available)       
  build_resolvers 1.5.1 (2.0.4 available)     
  build_runner_core 6.1.5 (7.1.0 available)   
  build_test 1.3.2 (2.1.3 available)
  build_web_compilers 2.12.2 (3.2.0 available)
  built_collection 4.3.2 (5.1.0 available)
  built_value 7.1.0 (8.1.1 available)
  charcode 1.1.3 (1.3.1 available)
  checked_yaml 1.0.4 (2.0.1 available)
  cli_repl 0.2.0+1 (0.2.2 available)
  cli_util 0.2.0 (0.3.3 available)
  code_builder 3.5.0 (4.1.0 available)
  collection 1.14.13 (1.15.0 available)
  convert 2.1.1 (3.0.1 available)
  coverage 0.14.2 (1.0.3 available)
  crypto 2.1.5 (3.0.1 available)
  csslib 0.16.2 (0.17.0 available)
  dart_browser_loader 0.0.6+1 (0.1.0 available)
  dart_style 1.3.10 (2.0.3 available)
  file 5.2.1 (6.1.2 available)
  fixnum 0.10.11 (1.0.0 available)
  glob 1.2.0 (2.0.1 available)
  graphs 0.2.0 (2.0.0 available)
  html 0.14.0+4 (0.15.0 available)
  http 0.12.2 (0.13.3 available)
  http_multi_server 2.2.0 (3.0.1 available)
  http_parser 3.1.4 (4.0.0 available)
  idb_shim 1.12.2+3 (2.0.0+2 available)
  intl 0.16.1 (0.17.0 available)
  io 0.3.4 (1.0.3 available)
  json_annotation 3.1.1 (4.1.0 available)
  logging 0.11.4 (1.0.1 available)
  matcher 0.12.9 (0.12.10 available)
  meta 1.2.4 (1.7.0 available)
  mime 0.9.7 (1.0.0 available)
  node_interop 1.2.1 (2.0.2 available)
  node_io 1.2.0 (2.1.0 available)
  node_preamble 1.4.12 (2.0.1 available)
  package_config 1.9.3 (2.0.0 available)
  package_resolver 1.0.10 (discontinued)
  path 1.7.0 (1.8.0 available)
  pedantic 1.9.2 (1.11.1 available)
  pool 1.4.0 (1.5.0 available)
  protobuf 1.1.0 (2.0.0 available)
  pub_semver 1.4.4 (2.0.0 available)
  pubspec_parse 0.1.7 (1.0.0 available)
  quiver 2.1.5 (3.0.1 available)
  sass 1.30.0 (1.37.5 available)
  sass_builder 2.1.3 (2.1.4 available)
  scratch_space 0.0.4+2 (1.0.0 available)
  sembast 2.4.10+4 (3.1.0+2 available)
  sembast_web 1.2.0+1 (2.0.0+2 available)
  shelf 0.7.9 (1.2.0 available)
  shelf_packages_handler 2.0.0 (3.0.0 available)
  shelf_static 0.2.9+1 (1.1.0 available)
  shelf_web_socket 0.2.3 (1.0.1 available)
  source_gen 0.9.10+1 (1.0.5 available)
  source_map_stack_trace 2.0.0 (2.1.0 available)
  source_maps 0.10.9 (0.10.10 available)
  source_span 1.7.0 (1.8.1 available)
  stack_trace 1.9.6 (1.10.0 available)
  stream_channel 2.0.0 (2.1.0 available)
  stream_transform 0.0.20 (2.0.0 available)
  string_scanner 1.0.5 (1.1.0 available)
  term_glyph 1.1.0 (1.2.0 available)
  test 1.15.7 (1.17.10 available)
  test_api 0.2.18+1 (0.4.2 available)
  test_core 0.3.11+4 (0.4.0 available)
  timing 0.1.1+3 (1.0.0 available)
  tuple 1.0.3 (2.0.0 available)
  typed_data 1.2.0 (1.3.0 available)
  uuid 2.2.2 (3.0.4 available)
  vm_service 4.2.0 (7.2.0 available)
  watcher 0.9.7+15 (1.0.0 available)
  web_socket_channel 1.1.0 (2.1.0 available)
  webkit_inspection_protocol 0.7.4 (1.0.0 available)
  yaml 2.2.1 (3.1.0 available)
Warning: You are using these overridden dependencies:
! build_runner 1.11.1+1 from git https://github.com/dart-lang/build.git at f7ffa0 in build_runner
Got dependencies!
PS D:\MyDartProjects\portal_turismo\turismo_browser> 
```

**Comment by jakemac53** [comment]
That makes sense, we are still logging these errors. If appears it is happening after every single build because of the output directory being updated.

It is continuing now though it looks like, which is good.

I am a bit concerned this will lead to some flakyness for you because there is some period of time presumably between the directory watcher crashing and being set back up, where we could miss some file events.

**Comment by jakemac53** [comment]
Actually this should only be for the build command generally that it even creates a build directory, so you should be ok in general (the file watchers are actually totally irrelevant here)

**Comment by jakemac53** [comment]
Published, and now merged master into here to update the main repo with this version.

**Pull request merged**
