### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by pkozlovskiy**

### CODE REVIEW

**Comment by jakemac53** [comment]
looks like an appveyor flake, re-running then ill merge assuming its happy

**Comment by jakemac53** [comment]
@pkozlovskiy are you able to sign the cla?

**Comment by pkozlovskiy** [comment]
> @pkozlovskiy are you able to sign the cla?



> @pkozlovskiy are you able to sign the cla?

I sign it after making PR, it is ok?

**Comment by jakemac53** [comment]
thanks!

**Pull request merged**
