### PR TITLE
Pass featureSet to SummaryBuilder.build

### PR DESCRIPTION
**Pull request by jakemac53**
I am unsure what I should actually be passing here.

What we really want is the feature set that is supported for the current running SDK version I think? But there is no api for that. As far as I can tell analyzer hardcodes the default feature set but its SDK constraint is not sufficient to make that valid.

### CODE REVIEW

**Comment by kevmoo** [comment]
QQ: does this change the lower bound of the SDK we use?

**Comment by scheglov** [comment]
You can get the set of features supported by a language version by creating `FeatureSet.fromEnableFlags([])` and then `restrictToVersion(languageVersion)`. Determining the running version of SDK and mapping it to the language version is up to the client.

**Comment by jakemac53** [comment]
It looks like we also need to bump our min analyzer version, any idea what version this was added in  @scheglov ?

**Comment by jakemac53** [comment]
also PTAL at the updated code

**Comment by scheglov** [comment]
The feature landed in https://dart-review.googlesource.com/c/sdk/+/132800, in 2020-01-22.
The [latest version](https://pub.dev/packages/analyzer/versions) of analyzer (`0.39.5`) should include it.

**Comment by jakemac53** [comment]
@kevmoo ya it looks like it does since we need the latest analyzer, updated everything to >=2.6.0

**Pull request merged**
