### PR TITLE
convert hyphens to $45 in ddc bootstrap code

### PR DESCRIPTION
**Pull request by jakemac53**
fixes https://github.com/dart-lang/build/issues/1523

### CODE REVIEW

**Comment by jakemac53** [comment]
cc @jmesserly is there something more sane we can do here?

Basically when bootstrapping ddc we have to try and recreate the original module name today, which is fairly error prone and has weird edge cases like this.

**Comment by jmesserly** [comment]
yes, DDC needs to export a good entry point: https://github.com/dart-lang/sdk/issues/31516

I'm looking into these issues generally. I have an old CL out that did address them (https://dart-review.googlesource.com/c/sdk/+/42885) ... but I need to find a migration path for internal code/anyone using the "legacy" module format.

it may be possible to fix #31516 first, if that would help you.

**Comment by jmesserly** [comment]
FYI, the relevant functions in DDC for escaping the library names are https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/analyzer/code_generator.dart#L6390 and https://github.com/dart-lang/sdk/blob/master/pkg/dev_compiler/lib/src/compiler/module_builder.dart#L324

**Comment by jakemac53** [comment]
I knew this was familiar haha.

Yes, resolving  dart-lang/sdk#31516 would help here, but if you have other plans coming down the pipeline I am happy to just copy the code you pointed at for now as well.

**Comment by jmesserly** [comment]
SGTM. Yeah I'm juggling a lot of things right now. :)

**Pull request merged**
